import { Product } from '@/types'

export const products: Product[] = [
  {
    id: 1,
    name: 'Linen Wrap Blouse',
    category: 'tops',
    cat: 'Tops',
    price: 89,
    oldPrice: 120,
    emoji: '👚',
    tag: 'New',
    color: '#E8E0D5',
    description: 'Effortlessly elegant linen wrap blouse with a relaxed silhouette. Perfect for warm days and evening occasions alike.',
    tags: ['linen', 'wrap', 'blouse', 'summer', 'casual', 'elegant', 'lightweight'],
  },
  {
    id: 2,
    name: 'Tailored Wide Trousers',
    category: 'bottoms',
    cat: 'Bottoms',
    price: 145,
    emoji: '👖',
    color: '#D5D0C8',
    description: 'Structured wide-leg trousers in a premium wool blend. A wardrobe cornerstone that transitions seamlessly from office to evening.',
    tags: ['trousers', 'wide-leg', 'tailored', 'wool', 'formal', 'office', 'structured'],
  },
  {
    id: 3,
    name: 'Cashmere Overcoat',
    category: 'outerwear',
    cat: 'Outerwear',
    price: 395,
    oldPrice: 480,
    emoji: '🧥',
    tag: 'Sale',
    color: '#C8BEB0',
    description: 'Luxurious pure cashmere overcoat with clean lines and a timeless silhouette. An heirloom-quality investment piece.',
    tags: ['cashmere', 'overcoat', 'winter', 'luxury', 'warm', 'coat', 'classic'],
  },
  {
    id: 4,
    name: 'Silk Scarf — Ivory',
    category: 'accessories',
    cat: 'Accessories',
    price: 65,
    emoji: '🧣',
    tag: 'New',
    color: '#EDE8E0',
    description: 'Hand-rolled pure silk scarf in a delicate ivory tone. Wear it around the neck, in your hair, or tied to a bag.',
    tags: ['silk', 'scarf', 'accessories', 'ivory', 'elegant', 'gift', 'versatile'],
  },
  {
    id: 5,
    name: 'Ribbed Knit Turtleneck',
    category: 'tops',
    cat: 'Tops',
    price: 110,
    emoji: '🧶',
    color: '#D8D0C5',
    description: 'Fine-ribbed merino wool turtleneck with a second-skin fit. The quintessential cold-weather staple.',
    tags: ['knit', 'turtleneck', 'merino', 'wool', 'winter', 'cozy', 'ribbed'],
  },
  {
    id: 6,
    name: 'Pleated Midi Skirt',
    category: 'bottoms',
    cat: 'Bottoms',
    price: 135,
    oldPrice: 160,
    emoji: '👗',
    tag: 'Sale',
    color: '#C5C0B8',
    description: 'Fluid pleated midi skirt in a matte crepe fabric. Moves beautifully and pairs with everything in your wardrobe.',
    tags: ['pleated', 'midi', 'skirt', 'crepe', 'elegant', 'flowy', 'versatile'],
  },
  {
    id: 7,
    name: 'Structured Blazer',
    category: 'outerwear',
    cat: 'Outerwear',
    price: 285,
    emoji: '🥼',
    tag: 'New',
    color: '#D0C8BE',
    description: 'Impeccably cut single-breasted blazer in Italian wool. The power piece your wardrobe demands.',
    tags: ['blazer', 'structured', 'wool', 'formal', 'office', 'italian', 'jacket'],
  },
  {
    id: 8,
    name: 'Leather Belt Bag',
    category: 'accessories',
    cat: 'Accessories',
    price: 175,
    oldPrice: 210,
    emoji: '👜',
    tag: 'Sale',
    color: '#C8C0B5',
    description: 'Vegetable-tanned Italian leather belt bag with gold hardware. Compact yet surprisingly spacious.',
    tags: ['leather', 'bag', 'accessories', 'belt bag', 'italian', 'gold', 'compact'],
  },
]
